[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://ilera-api-ot3r.onrender.com"

[[redirects]]
  from = "/"
  to = "/patient/"
  status = 302

[[redirects]]
  from = "/patient/*"
  to = "/patient/index.html"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/doctors/*"
  to = "/doctors/index.html"
  status = 200
